stages:
  - build
  - deploy

build:
  stage: build
  image: golang:1.19
  script:
    - go mod tidy
    - go build -o kirito
  artifacts:
    paths:
      - kirito

deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - echo "$KUBECONFIG" > kubeconfig
    - export KUBECONFIG=kubeconfig
    - kubectl apply -f kubernetes-deployment.yaml
